### ISSUE TITLE
Specify supported yarn version in Doc

### ISSUE THREAD

**Issue by inductor** [hashicorp-forge/hermes#10]
I get the following error with the latest yarn v1, which I believe most of developers who don't care much about next gen yarn have.

Expected version "~3.3.0" should be documented as well as node version.

```
$ make build
cd web; \
	yarn install; \
	rm -rf dist/; \
	yarn build;
yarn install v1.22.19
[1/5] 🔍  Validating package.json...
error hermes@1.0.0: The engine "yarn" is incompatible with this module. Expected version "~3.3.0". Got "1.22.19"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
yarn run v1.22.19
error hermes@1.0.0: The engine "yarn" is incompatible with this module. Expected version "~3.3.0". Got "1.22.19"
error Commands cannot run with an incompatible environment.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
make: *** [build-ui] Error 1
```

**Comment by psycle-james** [comment]
No expert, but my install script does something like this:

```bash
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
# Follow the instructions about adding the environment variables immediately, to saving having to log out and in again.

nvm install 14
npm install -g yarn
yarn set version stable
```
That way, I get Node version 14 (as specified) and it installs yarn and then switches to version 3.4.1 (which works) via the `yarn set version stable` thing; otherwise it's just v1.22.19...

**Comment by anubhavmishra** [comment]
@inductor You could try `yarn set version 3.3.0` and running `make build` again.

**Comment by inductor** [comment]
@anubhavmishra @psycle-james I know this works but what I'm suggesting here is doc improvement.

**Comment by inductor** [comment]
But personally it doesn't really make sense to me that this project's using a deprecated Node.js version while using yarn version which not many people are still using 😅

**Comment by psycle-james** [comment]
I quite agree on both counts - the docs could do with some tweaks, and the Node/yarn versions are also a bit unusual... but then I remember all the bizarre things going on in _my_ code, and I close my mouth again! 😄
