### ISSUE TITLE
Project name collision?

### ISSUE THREAD

**Issue by zyxist** [hashicorp-forge/hermes#11]
There is already a quite popular open-source project called "Hermes" in Java community: https://hermes.allegro.tech/ https://github.com/allegro/hermes which is more than 6 years old, and actively developed (not to mention yet another Hermes project from Facebook?). It's not a big issue, but have you researched the usage of the name before choosing it? What about users' confusion?

**Comment by anubhavmishra** [comment]
We researched the name beforehand and determined it was appropriate for the project. Thanks for your feedback.
