### ISSUE TITLE
Google API Scopes & Algolia - Security

### ISSUE THREAD

**Issue by nagireddygatla** [hashicorp-forge/hermes#139]
I'm trying to setup Hermes, need few clarifications on security aspects of Hermes. I read that we need to ensure below OAuth scopes for Production, which is essentially full access to all of Google Drive and Google Docs. Is my assumption right on that? Is that a security risk?
`https://www.googleapis.com/auth/directory.readonly,https://www.googleapis.com/auth/documents,https://www.googleapis.com/auth/drive,https://www.googleapis.com/auth/gmail.send`

I also see only below OAuth scope is required for localhost, whereas prod we need more OAuth scopes than this. Why is that?
`https://www.googleapis.com/auth/drive.readonly`

I see Hermes uses Algolia Search. Can we use Hermes without Algolia, or can we configure something else in place of Algolia, such as self hosted Elastic Search? Does configuring Algolia mean all of the Google Docs content is parsed to Algolia servers and is indexed to serve search capability? What are the endpoints of Algolia that Hermes hits to parse data to Algolia to index and search? Are these the only APIs?

`<MY_APP_ID>-dsn.algolia.net,
<MY_APP_ID>.algolianet.com`

Thank you!

**Comment by jfreda** [comment]
Hi @nagireddygatla, thanks for the questions!

> I'm trying to setup Hermes, need few clarifications on security aspects of Hermes. I read that we need to ensure below OAuth scopes for Production, which is essentially full access to all of Google Drive and Google Docs. Is my assumption right on that? Is that a security risk?
`https://www.googleapis.com/auth/directory.readonly,https://www.googleapis.com/auth/documents,https://www.googleapis.com/auth/drive,https://www.googleapis.com/auth/gmail.send`

Yes, these scopes are required for the server, not for users. Google does not provide more fine-grained auth scopes than these for the app's required functionality, and something like sharing a Google Drive folder with a service account that doesn't have these scopes does not work correctly (we tried 😅).

> I also see only below OAuth scope is required for localhost, whereas prod we need more OAuth scopes than this. Why is that?
`https://www.googleapis.com/auth/drive.readonly`

This is the OAuth scope that is prompted for Hermes users (vs. the server's scopes above). We actually can now update this to a narrower scope as of our recent release [v0.1.0](https://github.com/hashicorp-forge/hermes/releases/tag/v0.1.0) - thanks for the reminder!

> I see Hermes uses Algolia Search. Can we use Hermes without Algolia, or can we configure something else in place of Algolia, such as self hosted Elastic Search? Does configuring Algolia mean all of the Google Docs content is parsed to Algolia servers and is indexed to serve search capability? What are the endpoints of Algolia that Hermes hits to parse data to Algolia to index and search? Are these the only APIs?

Hermes currently strictly requires Algolia. We do not have plans to support other search providers, but it may become possible in the future with some effort if you wanted to fork the code. When Algolia is configured, yes all document content is indexed in Algolia, however it is worth noting that (when running Hermes via a built binary) all Algolia search queries are authenticated and proxied through the application backend.

Re: Algolia endpoints, we're using the [Algolia Go client library](https://github.com/algolia/algoliasearch-client-go) so I'll have to defer to Algolia docs for this info (not sure offhand if it could change based on the type of account, etc.).
