### ISSUE TITLE
Direct File Access with SMB or similar

### ISSUE THREAD

**Issue by mmeinesz** [hashicorp-forge/hermes#14]
You write that the documents are stored like /l/rfc/lab-123
Is there a way to access the files directly, via file server? Or would that corrupt the database?
Our company stores client data in projects, so file structure right now is /projects/PROJECTNUMBER/PROJECT-RELATED-Files
Could that be incorporated?

**Comment by jfreda** [comment]
Hi, thanks for the interest in Hermes! The `/l/rfc/lab-123` path is a URL for human-readable redirects to the corresponding documents – it's not related to how the documents are stored. Please refer to the [Google Drive](https://github.com/hashicorp-forge/hermes#google-drive) section of the README.md for more information on how the files are organized in Google Drive. It sounds like you're looking for the organized hierarchy of files in the "shortcuts folder" - however this structure ("{doc_type}/{product}/{document}") is not directly configurable at this time.

**Comment by mmeinesz** [comment]
thanks for your answer.
