### ISSUE TITLE
Can I use Hermes without Google Workspace account?

### ISSUE THREAD

**Issue by safe-bug** [hashicorp-forge/hermes#180]
Hello,

I would like to know if it is possible to use Hermes without a Google Workspace account, but only with a shared folder in Google Drive?

**Comment by jfreda** [comment]
👋 Hey @safe-bug! Sorry, Hermes requires a Google Workspace account because it interacts with a number of Google Workspace APIs (currently listed in bullet 3 [here](https://github.com/hashicorp-forge/hermes/blob/3f278d35c4178ef654373a22727c21e66c6306aa/README.md#google)).
