### ISSUE TITLE
Couldn't find the node_modules state file

### ISSUE THREAD

**Issue by JinsoRaj** [hashicorp-forge/hermes#23]
On running `make build` it shows: `Killed
Usage Error: Couldn't find the node_modules state file - running an install might help (findPackageLocation)`

I am using latest yarn and tried deleting `node_modules` and re installed with `yarn install`, tried with previous node LTS versions also. Couldn't fix :(

This is my `package.json` file:
![image](https://user-images.githubusercontent.com/48287817/216514425-c995606f-a517-44a3-a51c-4e17922569a7.png)

**Comment by jfreda** [comment]
Hi, thanks for your interest in Hermes! It looks like you're trying to do the `yarn install` from the root directory instead of the "web" directory, which contains the web application. The easiest solution would be to run `make web/install-deps`, which should hopefully fix your issue!

**Comment by JinsoRaj** [comment]
> 

This works fine in my local machine. But in digital ocean droplet the same error occurs. `Killed Usage Error: Couldn't find the node_modules state file - running an install might help (findPackageLocation)`
