### ISSUE TITLE
Separate frontend and backend?

### ISSUE THREAD

**Issue by inductor** [hashicorp-forge/hermes#41]
It looks like the current implementation heavily depends on golang binary itself, while frontend components are just built from yarn command and will be hosted in a static folder. Considering for performance and scalability I think that it should be able to hosted by an independent web server such as nginx or some cloud components like S3/GCS + CDN.

**Comment by inductor** [comment]
ref https://github.com/hashicorp-forge/hermes/blob/v0.0.1/web/web.go#L28

**Comment by m3ldis** [comment]
Hi inductor. You can host Golang binaries behind nginx like any other web application by creating a systemd service which runs the binary and passing all nginx traffic to it using the `proxy_pass` module in your server block.

For example, build the Hermes binary  and make a systemd file `hermessvc`:

```
[Unit]
Description=Hermes app

[Service]
Restart=always
RestartSec=5s
ExecStart=/location/of/your/binary 
 
[Install]
WantedBy=multi-user.target
```

Then run `systemctl daemon-reload && systemctl start hermessvc` to start the binary service.

Install nginx, and create `/etc/nginx/sites-available/hermes`:

```
server {
    server_name your_domain www.your_domain;

    location / {
        proxy_pass http://localhost:8000;
    }
}
```

Then link to it in sites-enabled and reload nginx.


Best.

**Comment by inductor** [comment]
@m3ldis I know, but I'm suggesting for solutions to provide the frontend separately such as using CDN.

**Comment by m3ldis** [comment]
This is really a devops question, not one about Hermes. You can do what you're asking without separating the two, and coupling front and back ends is quite common in fact.

But I'd have a look at one of the many examples online integrating CloudFront (AWS-native CDN) and EC2, like [this one](https://ashishkr99.medium.com/webserver-ec2-alb-efs-s3-and-cloudfront-provisioned-using-terraform-github-ef9dd64ef946) and [this one](https://hands-on.cloud/cloudfront-terraform-examples/#h-initial-setup-2), [Terraform's example](https://developer.hashicorp.com/terraform/tutorials/applications/cloudflare-static-website) using CloudFlare, or [Terraform's CloudFront](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudfront_distribution) module. 

You'd use an ami you create of the machine you set up with Hermes and nginx, of course, and you'd just have to set up a central database.

**Comment by inductor** [comment]
@m3ldis Thanks for the clarification and I agree that it's a DevOps question.
I think it is important for any potential users of Hermes to discuss about this somewhere at the end of the day. That's part of the reasons why I raised this issue :)

**Comment by jfreda** [comment]
Hi @inductor, thanks for the question! We currently don't have any plans to change from releasing a single binary with the embedded frontend application. I haven't tested this, but I _think_ something like this may work for your use case:

- Build the Hermes frontend by running `make web/build`.
- Store the contents of the `web/dist` directory in S3.
- Serve the backend somewhere using the Hermes binary.
- Configure CloudFront so the path pattern of `/api/*` is routed to the backend application, and the default is routed to the S3 origin hosting the frontend app.

Again, I haven't tested this approach at all so I'd be interested how it goes 🙂 And just out of curiosity, if you're running Hermes at the scale where you feel this is necessary to improve performance, we'd be very interested to hear about how you're using it!
