### ISSUE TITLE
Meilisearch as an algolia alternative

### ISSUE THREAD

**Issue by adewaleafolabi** [hashicorp-forge/hermes#449]
Thank you for the fantastic work done here. Hashicorp opensource has been overall wonderful. I recently needed to start keeping track of documents and ideas and I found hermes. 

I'd like to make a suggestion as regards the search engine. Would we be interested in switching or providing the option of letting the user pick the search engine ? I'd like to recommend [meilisearch](www.meilisearch.com). 

1. it's [open source ](https://github.com/meilisearch) and can be self-hosted
2. the syntax and spirit is pretty much the same as Algolia

**Comment by jfreda** [comment]
👋 Hi @adewaleafolabi, thanks for the kind words and the interest in Hermes! Unfortunately we don't currently have the resources to support other search engines besides Algolia, which is pretty tied into Hermes. Until the search engine is made pluggable (which is not currently planned), the only option will be to fork Hermes and try to replace the Algolia pieces, sorry!
