### ISSUE TITLE
Plan for alternative document provider

### ISSUE THREAD

**Issue by luxifer** [hashicorp-forge/hermes#81]
Hi!

First of all, I believe this kind of solution on top on existing document provider is great! It allows centralizing templates, status and sharing in one place, without being dependent on the document provider.

With that in mind, is there any plan to allow another document provider like MS SharePoint or even open source one like NextCloud?

And if it's planned, do you accept PR for that kind of proposal?

Regards

**Comment by anubhavmishra** [comment]
Thanks for the interest in Hermes! Unfortunately, we feel that the code base is currently too tied into Google Workspace at the moment. However, we are planning some refactors in the future. We can't support other document platforms at time time but we're attaching the integrations label to this issue so we can revisit it. Thanks again!
