### ISSUE TITLE
Error initializing Algolia write client

### ISSUE THREAD

**Issue by ia-mfriegang** [hashicorp-forge/hermes#83]
I configured Hermes as per the docs, but I seem to be getting an error with Algolia. The full error looks like this:
```
error initializing Algolia write client: error setting settings for docs index: all hosts have been contacted unsuccessfully, it can either be a server or a network err
or or wrong appID/key credentials were used. You can use opt.ExposeIntermediateNetworkErrors(true) to investigate.
```

As far as I can tell, my Algolia section of the config looks to be correct. The only part I was a bit unclear on was the `write_api_key`, I assume this is meant to be the Admin API Key?

I've tested connectivity to various Algolia endpoints with netcat, and seem to be able to connect over port 443 fine:
- <MY_APP_ID>-dsn.algolia.net
- <MY_APP_ID-1>.algolianet.com
- <MY_APP_ID-2>.algolianet.com
- <MY_APP_ID>-3.algolianet.com

I didn't see any options related to `opt.ExposeIntermediateNetworkErrors(true)` in the config, so I assume thats something that needs to be passed to the Go client?

Any advice on this would be greatly appreciated.

**Comment by anubhavmishra** [comment]
@ia-mfriegang thanks for your question and sorry for the delayed response. The `write_api_key` is different from the Admin API key. You can find the "Write API Key" in your Algolia settings in the "API Keys" section. Hope this helps?

**Comment by ia-mfriegang** [comment]
Thanks @anubhavmishra , it looks like I somehow had the wrong ` write_api_key` set. It works as expected with the correct key 😄

**Comment by anubhavmishra** [comment]
@ia-mfriegang I glad that works for you! Closing this one. 🙏🏽
